<?php

namespace App\Filament\Resources\Warehouses\Schemas;

use App\Services\StockService;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class WarehouseForm
{
    public static function configure(Schema $schema, ?StockService $stockService = null): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->required()
                    ->unique(ignoreRecord: true)
                    ->maxLength(255),
                TextInput::make('code')
                    ->required()
                    ->unique(ignoreRecord: true)
                    ->maxLength(50),
                Checkbox::make('is_active')
                    ->label('Active')
                    ->default(true),
                TextEntry::make('warehouse_stock_summary')
                    ->state(function () use ($stockService) {
                        $service = $stockService ?? app(StockService::class);

                        return 'Warehouse stock metrics are generated by StockService and will be visible after warehouse creation or on linked stock records.';
                    }),
            ]);
    }
}
